name: delivery_system
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  appwrite: ^0.7.0
  auto_route: ^2.2.0
  cupertino_icons: ^1.0.3
  dartz: ^0.10.0-nullsafety.2
  dio: ^4.0.0
  flutter:
    sdk: flutter

  flutter_bloc: ^7.0.1
  freezed_annotation: ^0.14.2
  get_it: ^7.1.3
  injectable: ^1.4.1
  # ui
  intl: ^0.17.0
  timeline_tile: ^2.0.0
  
dev_dependencies:
  auto_route_generator: ^2.1.0
  build_runner: ^2.0.5
  flutter_test:
    sdk: flutter
  freezed: ^0.14.2
  injectable_generator: ^1.4.1
  json_serializable: ^4.1.3
  lint: ^1.5.3
flutter:
  uses-material-design: true
